### PR TITLE
[OPS-7459] add and configure user_expire

### PR DESCRIPTION
**Pull request by lazysoundsystem**
https://humanitarian.atlassian.net/browse/OPS-7459

Adds and configures user_expire module using, to start, timing taken from the UNOCHA.org and HRinfo sites:
Time to expire users: 13 months
Time for warnings before expiry: 14 days and 2 days.

I also updated a couple of other modules that have been updated elsewhere, (though will keep these for separate commits on other sites): social_auth_hid, pathauto, drupal/console

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
@cafuego I got a bit confused in the conversation on https://humanitarian.atlassian.net/browse/OPS-8113 - I'd already made this PR, but have adjusted the timings as per Emma's mail - 6 months of inactivity, with a warning notice seven days before expiry. This also sets the frequency to give a second reminder 2 days before the account expires (as suggested by Marina on https://humanitarian.atlassian.net/browse/OPS-7459 )

I've also prepared similar PRs (without updating other modules) for all the other sites (with the exception of GMS as I haven't set up my stack locally yet). Should I push those for review?

**Comment by cafuego** [comment]
@lazysoundsystem Aha, a secret other PR!

I've changed the timing defaults on the Ansible PR for OPS-8113 so they now match what you're setting here. Yes, you can push the other properties and demand reviews :-)

**Review by cafuego — APPROVED** [review]
Approved with two patches that make user_expire work a lot less badly. These are present on Sesame and have thus been tested. I would suggest you also pop them on all other Drupal 8/9 sites that get user_expire.

**Comment by cafuego** [comment]
I've had to drop the external_entities patches, as they no longer applied. The first one was merged into the new 8.x-2.x-alpha4 but the code for the second one seems ... gone. So definitely check whatever was broken that was supposed to be fixed by https://www.drupal.org/project/external_entities/issues/3230638#comment-14205286

**Comment by attiks** [comment]
This needs proper testing, the boolean fix was added to beta4, but other things have changed as well

**Comment by attiks** [comment]
- https://www.drupal.org/project/external_entities/issues/3262870#comment-14464020
- https://www.drupal.org/project/external_entities/issues/3272698#comment-14464312

**Comment by lazysoundsystem** [comment]
Created another PR - https://github.com/UN-OCHA/assessmentregistry8-site/pull/372 - with just the user_expire part so we can test the changes to external_entities separately, if that helps.

**Comment by lazysoundsystem** [comment]
Closing as we're using https://github.com/UN-OCHA/assessmentregistry8-site/pull/372 instead. Will create a separate PR for the module updates.

**Pull request closed without merging**
