### PR TITLE
DOC-45 KM form styling

### PR DESCRIPTION
**Pull request by left23**
I've done a first pass for basic styling for the KM

**KM form**
Screenshot_2021-03-03 Edit km Interim guidance Scaling-up COVID-19 outbreak readiness and response operations in humanitari

KM view
Screenshot_2021-03-03 Interim guidance Scaling-up COVID-19 outbreak readiness and response operations in humanitarian situa

KM table layout
Screenshot_2021-03-03 kms Assessment Analysis Knowledge Management Platform

This PR depends on the `cd-226-design-system` base theme branch, which is currently without a release (in active development, the yellow background in the screenshots is from the base theme and there for testing purposes). I tend to `cd` into `themes/contrib/common_design` , remove the base theme directory, clone from https://github.com/UN-OCHA/common_design/ and switch branches `git checkout -b cd-226-design-system origin/cd-226-design-system`. 

However, I should try to use the same technique as the CD Feature site which deploys the `cd-226-design-system` branch of the base theme. https://github.com/UN-OCHA/common-design-site/blob/cd-226-design-system/composer.json#L120
There are implications to this, specifically (IIRC) that the composer.lock should be removed to force the composer.json be used on deploy.

Without the `cd-226-design-system` base theme branch, there will be no full width header and footer (not really relevant to Docstore stuff) and I would also expect some styling not to show up nicely, because I am using some new component styles.

@attiks I've merged the PR I have open for the base theme update into the feature/docstore branch in order to deliver all this together. As part of this work, I've moved the Blocks from the sidebar region to the facets regions so you should do a `drush cim`.

### CODE REVIEW

**Comment by left23** [comment]
@attiks I attempted to bring in the base theme feature branch with composer, as you can see in the commits above. The build fails due to memory allowance.

I'm not sure where to go from here in the short term. I can create a base theme release soon even in the base theme is not quite ready, so we can deploy this for testing before deploying, but I'm not quite ready yet.

FYI @cafuego Do you have any thoughts on this? Is using a feature branch of the base theme reasonable in this scenario?

**Comment by emmajane** [comment]
Excellent first pass, @left23 !! Already looking much more tidy. The only thing that looks a bit confusing to me is the "show row weights". I'm not sure if they're using the standard Drupal placement but they feel high to me making me wonder which form element they belong to (mostly a problem where the item previous also has row weights... "is it too low, or is it too high?")

**Comment by left23** [comment]
I've adjusted the "Show row weights" button to align with the Field label, as seen below. Also note the table styles are being picked up from the `cd-table` classes I added to the generic `/dataset/table` template override.
Screenshot_2021-03-04 Edit km Interim guidance Scaling-up COVID-19 outbreak readiness and response operations in humanitari

@attiks I'm adding you as reviewer. Since we have the travis issue fixed, let me know if you want me to merge this. It might be easier to see what's left to be done if everything is together on the feature site. And please point out specific things or pages that I might be missing.

**Review by attiks — APPROVED** [review]
Merge it!

**Comment by emmajane** [comment]
@left23 Yummy! This is easier for my eye to follow now. Thanks!

**Pull request merged**
